name: mobile_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0   # ✅ Updated for latest null-safety and DateFormat support
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

# ✅ Custom app icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/Icons/wallet-icon2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Icons/wallet-icon2.png
    - assets/Icons/notification.png
    - assets/Icons/wallet_folder.png
    - assets/Icons/navigation_icons/nav_history.png
    - assets/Icons/navigation_icons/nav_home.png
    - assets/Icons/navigation_icons/nav_profile.png
    - assets/Icons/navigation_icons/nav_wallet.png
    - assets/profile_pictures/ituh_logo.jpg
    - assets/Icons/dropdown.png
    - assets/Fonts/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/Fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600

    - family: PlayFairDisplay
      fonts:
        - asset: assets/Fonts/PlayFair/PlayFairDisplay-Regular.ttf
          weight: 400
        - asset: assets/Fonts/PlayFair/PlayFairDisplay-Italic.ttf
          style: italic   # ✅ Added style for italic variant
